apiVersion: v1
kind: ServiceAccount
metadata:
  name: wp-admin
  namespace: wp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wp-admin-role
  namespace: wp
rules:
- apiGroups: [""]
  resources: ["pods","services","configmaps","persistentvolumeclaims","serviceaccounts","secrets"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["policy"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wp-admin-rolebinding
  namespace: wp
subjects:
- kind: User
  name: paul
roleRef:
  kind: Role
  name: wp-admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: wp-admin
  namespace: wp
  annotations:
    kubernetes.io/service-account.name: wp-admin
type: kubernetes.io/service-account-token
