apiVersion: v1
kind: ServiceAccount
metadata:
  name: wp-mariadb
  namespace: wp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wp-wordpress
  namespace: wp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wp-runtime-role
  namespace: wp
rules:
- apiGroups: [""]
  resources: ["pods","services","configmaps","persistentvolumeclaims","serviceaccounts","secrets"]
  verbs: ["get","list","watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["get","list","watch"]
- apiGroups: ["policy"]
  resources: ["*"]
  verbs: ["get","list","watch"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wp-runtime-rolebinding
  namespace: wp
subjects:
- kind: ServiceAccount
  name: wp-mariadb
- kind: ServiceAccount
  name: wp-wordpress
roleRef:
  kind: Role
  name: wp-runtime-role
  apiGroup: rbac.authorization.k8s.io
